### PR TITLE
removed unecessary character from index.md

### LINKED ISSUE #26: unecessary character ' * ' in the index.md
The index.md and subsequently https://owasp.org/www-project-csrfguard/  have a ' * '
Screenshot from 2021-10-03 02-51-41

 which makes one think there's a condition there but I think there isn't any and it's a case of typo.

### PR DESCRIPTION
**Pull request by shubhangi013**
Fixes #26 .

### CODE REVIEW

**Comment by forgedhallpass** [comment]
@shubhangi013 Thank you for pointing this out, but creating a ticket + PR takes more effort than removing one character. If you'd like to contribute let me know and we can think of something.

**Comment by shubhangi013** [comment]
> @shubhangi013 Thank you for pointing this out, but creating a ticket + PR takes more effort than removing one character. If you'd like to contribute let me know and we can think of something.

Oh right. I understand it completely. 
Yes I'd like to contribute! :smile:

**Comment by forgedhallpass** [comment]
@shubhangi013 

Depending on your technical knowledge, you could do some of the following:
* add unit tests (the easiest way to understand the logic)
* try different configuration options and search for corner/cases bugs
* add new/missing testing scenarios in the test application

If you have played around enough with the application to understand the inner workings, you can also help making the technical documentation for the [possible configurations](https://github.com/OWASP/www-project-csrfguard/blob/master/csrfguard/src/main/resources/csrfguard.properties) better. 

Depending on your skill set and technical background, you could also start working on an existing issue/enhancement. I've created a few just now.

Let me know if you need any help, and good luck!

**Comment by shubhangi013** [comment]
> @shubhangi013
> 
> Depending on your technical knowledge, you could do some of the following:
> 
>     * add unit tests (the easiest way to understand the logic)
> 
>     * try different configuration options and search for corner/cases bugs
> 
>     * add new/missing testing scenarios in the test application
> 
> 
> If you have played around enough with the application to understand the inner workings, you can also help making the technical documentation for the [possible configurations](https://github.com/OWASP/www-project-csrfguard/blob/master/csrfguard/src/main/resources/csrfguard.properties) better.
> 
> Depending on your skill set and technical background, you could also start working on an existing issue/enhancement. I've created a few just now.
> 
> Let me know if you need any help, and good luck!

Oh I'll try and contribute! Thankyou so much for this :smiley:

**Pull request closed without merging**
