### PR TITLE
[8] make CsrfGuardFilter a non final class so that it can be extended

### PR DESCRIPTION
**Pull request by deepak229**

### CODE REVIEW

**Comment by deepak229** [comment]
I see the change already being commited by @forgedhallpass . Closing this PR.

**Comment by forgedhallpass** [comment]
At your issue request I've made the modification already. Thought you were having problems creating a PR, otherwise I would have waited and ccepted it. It's good to know that there are no such problems :)

**Comment by deepak229** [comment]
@forgedhallpass , do you know when will this change be available in the jars published to maven repo?

**Comment by forgedhallpass** [comment]
@deepak229 I am using the project already in two production environments, but in-depth testing was done only on the configuration needed by my projects. I've tried covering all the functionalities separately and extended the test web application, but there are a lot of possible combinations on how you can configure CSRFGuard, hence I've currently created a release candidate version, that can be downloaded from the releases page (the minor change of removing the final modifier from the servlet filter is not included there yet). I'd recommend you cloning the latest version of the repository, and creating the jars for yourself. It should take like 5 minutes of your time, and then you can provide me some feedback. If everything goes as expected, I will create an official release and will deploy it to the maven central as well (I've already started the process, but I need to wait until I'll be given the necessary permissions to do so.)

**Comment by deepak229** [comment]
@forgedhallpass ,  I was able to build it and test it locally. I was able to extend add my business logic as needed. We are currently using 3.1.0 and we look forward to use 4.0 as soon as it is available. Thanks!

**Pull request closed without merging**
