### PR TITLE
Updated documentation - Open Issue

### PR DESCRIPTION
**Pull request by swetak20**
Updated Documentation as per Issue #36

### CODE REVIEW

**Review by forgedhallpass — CHANGES_REQUESTED** [review]
Hello @swetak20,

Thank you for taking the time to contribute to the project, but unfortunately changing the URL is not enough. Please read the ticket. All the content from https://wiki.owasp.org/index.php/CSRFGuard_3_Token_Injection should be moved to this GitHub repository (correctly formatted), so it would show on the https://owasp.org/www-project-csrfguard/ page.

**Comment by swetak20** [comment]
I was working on migrating the contents of [https://owasp.org/www-project-csrfguard/], and I believe it is currently generated from index.md. Could you confirm if this is correct?

**Comment by swetak20** [comment]
I was checking the link in [https://wiki.owasp.org/index.php/CSRFGuard_3_Token_Injection](https://wiki.owasp.org/index.php/CSRFGuard_3_Token_Injection) before migrating them, and they redirect to a 404.
Example - [Owasp.CsrfGuard.Test](https://github.com/esheri3/OWASP-CSRFGuard/tree/master/Owasp.CsrfGuard.Test)

Could you suggest what should we cite the sources as in the updated documentation?

**Comment by forgedhallpass** [comment]
> I was working on migrating the contents to https://owasp.org/www-project-csrfguard/ and I believe it is currently generated from index.md. Could you confirm if this is correct?

Yes, the documentation is generated from the markdown files.

**Comment by forgedhallpass** [comment]
> I was checking the link in https://wiki.owasp.org/index.php/CSRFGuard_3_Token_Injection before migrating them, and they redirect to a 404. Example - [Owasp.CsrfGuard.Test](https://github.com/esheri3/OWASP-CSRFGuard/tree/master/Owasp.CsrfGuard.Test)
> 
> Could you suggest what should we cite the sources as in the updated documentation?

The test properties files can be found in the following folder in the repository: https://github.com/OWASP/www-project-csrfguard/tree/master/csrfguard-test/csrfguard-test-jsp/src/main/webapp/WEB-INF/classes
The properties file also contains a lot of documentation in-line.

**Comment by swetak20** [comment]
@forgedhallpass  I've made the requested changes. Please review the updates and let me know if there are any further adjustments needed.

**Pull request merged**
